genre_mapping = {
    "1st grade": "elementary",
    "2nd grade": "elementary",
    "adult colouring books": "adult",
    "adult fiction": "adult",
    "african literature": "africa",
    "african american literature": "african american",
    "african-american literature": "african american",
    "american revolution": "american",
    "american history": "american",
    "anthologies": "anthology",
    "anthropological fiction": "anthropology",
    "art history": "art",
    "asian literature": "asia",
    "autobiographical fiction": "autobiography",
    "back to school": "school",
    "banned books": "",
    "bande dessinée": "comic book",
    "biography memoir": "biography",
    "challenged books": "",
    "chaotic cat adventures": "cats",
    "children's fantasy": "childrens",
    "children's health": "childrens",
    "children's horror": "childrens",
    "children's literature": "childrens",
    "children's non-fiction": "childrens",
    "children's picture book": "childrens",
    "childrens non-fiction": "childrens",
    "childrens picture book": "childrens",
    "christian": "christianity",
    "christian fiction": "christianity",
    "colouring books": "colouring",
    "comics": "comic book",
    "coming-of-age": "coming of age",
    "coming-of-age novel": "coming of age",
    "contemporary fiction": "contemporary",
    "contemporary romance": "contemporary",
    "dark comedy": "comedy",
    "dark humor": "dark",
    "dc comics": "comic book",
    "dragonlance": "dragons",
    "epic fantasy": "epic",
    "erotic fiction": "erotica",
    "erotic romance": "erotica",
    "fairies": "fae",
    "fairy tale retellings": "fairy tales",
    "fantasy romance": "fantasy",
    "flash fiction": "fiction",
    "folk tales": "folklore",
    "french literature": "france",
    "gender identity": "gender",
    "gender roles": "gender",
    "german literature": "germany",
    "graphic novels": "graphic novel",
    "graphic novels comics": "graphic novel",
    "graphic novels manga": "graphic novel",
    "harlequin presents": "harlequin",
    "historical fantasy": "historical",
    "historical fiction": "historical",
    "historical mystery": "historical",
    "historical romance": "historical",
    "history": "historical",
    "humorous": "humor",
    "humorous fiction": "humor",
    "indian literature": "india",
    "irish literature": "ireland",
    "japanese literature": "japan",
    "jewish": "judaism",
    "juvenile fiction": "juvenile",
    "latin american literature": "latin american",
    "latino": "latin american",
    "legal thriller": "law",
    "lgbtq+ themes": "lgbt",
    "lgbtq+ youth": "lgbt",
    "literature": "",
    "magical realism": "magic",
    "medicine": "medical",
    "mental illness": "mental health",
    "military fiction": "military",
    "military history": "military",
    "military science fiction": "military",
    "mystery thriller": "mystery",
    "nan": "",
    "native americans": "native american",
    "nonfiction": "non-fiction",
    "novels": "",
    "paranormal romance": "paranormal",
    "political fiction": "politics",
    "political manifesto": "politics",
    "prehistoric fiction": "prehistoric",
    "prehistory": "prehistoric",
    "psychological drama": "psychology",
    "psychological thriller": "psychology",
    "read for school": "school",
    "romantasy": "romance",
    "romantic suspense": "romance",
    "russian history": "russia",
    "russian literature": "russia",
    "satirical science fiction": "science fiction",
    "school stories": "school",
    "science fiction fantasy": "science fiction",
    "short story collection": "short stories",
    "social commentary": "social",
    "social issues": "social",
    "social justice": "social",
    "social themes": "social",
    "social work": "social",
    "sociology": "social",
    "space opera": "space",
    "spanish literature": "spain",
    "speculative fiction": "fiction",
    "sports journalism": "sports",
    "sports romance": "sports",
    "the united states of america": "american",
    "urban fantasy": "urban",
    "war novel": "war",
    "western romance": "romance",
    "women's studies": "womens",
    "womens fiction": "womens",
    "womens studies": "womens",
    "young adult contemporary": "young adult",
    "young adult fantasy": "young adult",
    "young adult fiction": "young adult",
    "young adult historical fiction": "young adult",
    "young adult literature": "young adult",
    "young adult mystery": "young adult",
    "young adult paranormal romance": "young adult",
    "young adult romance": "young adult"
}

def map_genre(word):
    return genre_mapping.get(word, word)